---
- name: configure_elastic | Load Vars
  include_vars: "main.yml"

- name: configure_elastic | Configure Listening IP and Port
  lineinfile:
    path: "{{ elastic_conf }}"
    state: present
    create: yes
    mode: 0644
    owner: root
    group: elasticsearch
    line: '{{ item }}'
  with_items:
    - 'network.host: "{{ server_ip }}"'
    - 'http.port: {{ elastic_port }}'

- name: configure_elastic | Start the Elastic Service
  service:
    name: elasticsearch
    enabled: true
    state: started
