---
- name: configure_elastic | Configure Listening IP and Port
  lineinfile:
    path: "{{ elastic_conf }}"
    state: present
    create: yes
    mode: 0644
    owner: root
    group: elasticsearch
    # FIXME: this interprets the key as a regex, which is not correct
    regexp: '^{{ item.key }}: .*'
    line: '{{ item.key }}: {{ item.value }}'
  loop:
    - { key: 'network.host'                     , value: '"{{ inventory_hostname }}"' }
    - { key: 'http.port'                        , value: '{{ elastic_port }}' }
    - { key: 'xpack.license.self_generated.type', value: 'basic' }
    - { key: 'cluster.initial_master_nodes'     , value: '["{{ cluster_initial_master_nodes | list | join(''", "'') }}"]' }
    - { key: 'discovery.seed_hosts'             , value: '["{{ cluster_initial_master_nodes | list | join(''", "'') }}"]' }
    - { key: 'node.master'                      , value: '{{ inventory_hostname in groups[''ElasticsearchMasters''] | lower }}' }
    - { key: 'node.data'                        , value: '{{ inventory_hostname in groups[''ElasticsearchDataNodes''] | lower }}' }
    - { key: 'node.ingest'                      , value: '{{ inventory_hostname in groups[''ElasticsearchDataNodes''] | lower }}' }
    - { key: 'network.bind_host'                , value: '0.0.0.0' }

- name: configure_elastic | Configure SSL For Elasticsearch (if SSL True)
  lineinfile:
    path: "{{ elastic_conf }}"
    state: present
    line: "{{ item }}"
  loop:
    - "xpack.security.enabled: true"
    - "xpack.security.http.ssl.enabled: true"
    - "xpack.security.transport.ssl.enabled: true"
    - "xpack.security.transport.ssl.verification_mode: certificate"
    - "xpack.security.http.ssl.key: {{ elastic_cert_location }}{{ cert_pem_key_name }}"
    - "xpack.security.http.ssl.certificate: {{ elastic_cert_location }}{{ cert_pem_crt_name }}"
    - 'xpack.security.http.ssl.certificate_authorities: ["{{ elastic_cert_location }}{{ cert_ca_chain_name }}"]'
  when: ssl_on|bool

- name: configure_elastic | Start the Elastic Service
  service:
    name: elasticsearch
    enabled: true
    state: started
