---

- name: install_sw_Debian | Install Java
  apt:
    name:
      - openjdk-11-jre-headless
      - openjdk-11-jdk-headless
      - apt-transport-https
    state: latest

- name: install_sw_Debian | Grab Public Signing Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: install_sw_Debian | Add Elastic Apt Repo
  lineinfile:
    path: /etc/apt/sources.list.d/elastic.list
    state: present
    create: true
    backup: true
    mode: 0644
    owner: root
    group: root
    line: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"

- name: install_sw_Debian | Add Elastic Curator Apt Repo
  lineinfile:
    path: /etc/apt/sources.list.d/elastic.list
    state: present
    create: true
    backup: true
    mode: 0644
    owner: root
    group: root
    line: "deb [arch=amd64] https://packages.elastic.co/curator/5/debian stable main"
  when: inventory_hostname in groups['ElasticsearchMasters'] or inventory_hostname in groups['ElasticsearchDataNodes']

- name: install_sw_Debian | Install Elastic SW
  apt:
    name:
      - elasticsearch
      - elasticsearch-curator
    update_cache: true
    state: latest
  when: inventory_hostname in groups['ElasticsearchMasters'] or inventory_hostname in groups['ElasticsearchDataNodes']

- name: install_sw_Debian | Install Logstash SW
  apt:
    name:
      - logstash
    update_cache: true
    state: latest
  when: inventory_hostname in groups['Logstash']

- name: install_sw_Debian | Install Kibana SW
  apt:
    name:
      - kibana
    update_cache: true
    state: latest
  when: inventory_hostname in groups['Kibana']

- name: install_sw_Debian | Open Firewall Ports For Non-Localhost
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ elastic_port }}"
    - "{{ kibana_port }}"
  when: server_ip != "localhost"

- name: install_sw_Debian | Open Beats Port Regardless of Install IP
  ufw:
    rule: allow
    port: "{{ beat_port }}"
    proto: tcp
