---
# defaults file for ELK_Stack
auditbeat_conf: /etc/auditbeat/auditbeat.yml
auditbeat_template_path: /etc/logstash/templates/auditbeats.json
beat_port: 5044
curator_conf: /etc/curator/curator.yml
curator_delete_conf: /etc/curator/delete_indices.yml
delete_after_days: 365
elastic_conf: /etc/elasticsearch/elasticsearch.yml
elastic_port: 9200
filebeat_conf: /etc/filebeat/filebeat.yml
filebeat_template_path: /etc/logstash/templates/filebeats.json
kibana_conf: /etc/kibana/kibana.yml
kibana_port: 5601
logstash_beat_conf: /etc/logstash/conf.d/01-beats-input.conf
logstash_output_conf: /etc/logstash/conf.d/30-elasticsearch-output.conf
logstash_sysfilter_conf: /etc/logstash/conf.d/10-syslog-filter.conf
replicas: 0
server_ip: localhost
shards: 1

#SSL Settings
ssl_on: false
cert_location: /etc/ssl/
elastic_cert_location: /etc/elasticsearch/certs/
kibana_cert_location: /etc/kibana/certs/
logstash_cert_location: /etc/logstash/certs/
